name: find_repo
description: Search repositories and issues
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  auto_route: 5.0.2
  bloc: 8.1.0
  cupertino_icons: 1.0.5
  dio: 4.0.6
  easy_localization: 3.0.1
  equatable: 2.0.5
  fimber: 0.6.6
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_portal: 1.1.1
  get_it: 7.2.0
  google_fonts: 3.0.1
  http: 0.13.5
  injectable: 1.5.3
  json_annotation: 4.7.0
  pretty_dio_logger: 1.2.0-beta-1
  provider: 6.0.4
  retrofit: 3.3.1
  rxdart: 0.27.5

dev_dependencies:
  auto_route_generator: 5.0.2
  build_runner: 2.3.2
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: 1.5.4
  json_serializable: 6.5.3
  lint: 1.10.0
  retrofit_generator: 4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
