name: fh_home_coding
description: FutureHome - recruitment task

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: 1.0.5
  easy_localization: 3.0.1
  flutter:
    sdk: flutter
  google_fonts: 3.0.1
  provider: 6.0.4

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  lint: 1.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
